"""
SwasthAI Guardian - Disease Prediction Model Training Script
Trains a Random Forest on rural India disease symptoms.
Run once: python train_disease_model.py
"""
import pandas as pd, joblib
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import Pipeline

TRAINING_DATA = [
    # TYPHOID - 50 samples
    ("high fever sustained days headache weakness stomach pain loss appetite", "Typhoid"),
    ("continuous fever body weakness abdomen pain no hunger nausea", "Typhoid"),
    ("fever one week headache diarrhea fatigue rose spots skin", "Typhoid"),
    ("bukhar sar dard kamzori pet dard bhook nahi", "Typhoid"),
    ("sustained high temperature chills constipation spleen enlarged", "Typhoid"),
    ("prolonged fever week abdominal tenderness lethargy coated tongue", "Typhoid"),
    ("fever stepwise increasing temperature mild cough stomach bloating", "Typhoid"),
    ("enteric fever high temperature headache slow pulse rose rash", "Typhoid"),
    ("high grade fever one week nausea vomiting abdominal discomfort weakness", "Typhoid"),
    ("continuous high fever constipation abdominal pain headache no appetite", "Typhoid"),
    ("salmonella fever prolonged weakness stomach pain loss appetite", "Typhoid"),
    ("week long fever fatigue stomach tenderness headache pale stool", "Typhoid"),
    ("fever nahi ja raha pet mein dard kamzori bhook nahi", "Typhoid"),
    ("seven day fever headache body ache stomach upset", "Typhoid"),
    ("persistent fever dull headache abdominal discomfort fatigue weakness", "Typhoid"),
    ("high fever abdominal bloating constipation body weakness no appetite", "Typhoid"),
    ("stepped fever week abdominal cramps fatigue headache", "Typhoid"),
    ("bukhar ek hafte se headache kamzori pet mein takleef", "Typhoid"),
    ("enteric fever sustained temperature constipation weakness abdominal pain", "Typhoid"),
    ("prolonged high temperature stomach discomfort no hunger weakness", "Typhoid"),
    ("high fever stomach pain and constipation for 10 days", "Typhoid"),
    ("bukhar jo hafte se kam nahi ho raha aur pet dard", "Typhoid"),
    ("typhoid symptoms persistent fever and abdominal ache", "Typhoid"),
    ("fever stomach pain loss of appetite and weakness", "Typhoid"),
    ("ek hafte se bukhar aur pet mein marode", "Typhoid"),
    ("sustained high temp with stomach discomfort and thakaan", "Typhoid"),
    ("typhoid signs long fever and abdominal cramps", "Typhoid"),
    ("bukhar hafte bhar se aur pet mein dard kamzori", "Typhoid"),
    ("prolonged fever stomach pain and constipation signs", "Typhoid"),
    ("typhoid infection high temp and abdominal pain", "Typhoid"),
    ("bukhar jo theek nahi ho raha pet mein dard", "Typhoid"),
    ("high fever for 1 week stomach ache and fatigue", "Typhoid"),
    ("persistent fever abdominal pain and weakness typhoid", "Typhoid"),
    ("bukhar aur pet dard hafte bhar se typhoid", "Typhoid"),
    ("sustained fever stomach discomfort constipation typhoid", "Typhoid"),
    ("long fever stomach pain loss of appetite typhoid", "Typhoid"),
    ("typhoid symptoms persistent high temperature thakaan", "Typhoid"),
    ("bukhar jo hafte se chal raha hai pet mein dard", "Typhoid"),
    ("prolonged fever abdominal ache weakness signs", "Typhoid"),
    ("typhoid signs sustained high fever and stomach pain", "Typhoid"),
    ("bukhar hafte se badh raha hai pet mein takleef", "Typhoid"),
    ("high fever for many days stomach pain and thakaan", "Typhoid"),
    ("persistent fever stomach discomfort and weakness", "Typhoid"),
    ("bukhar hafte se kam nahi ho raha pet mein dard", "Typhoid"),
    ("sustained fever abdominal pain loss of appetite signs", "Typhoid"),
    ("long fever stomach pain and fatigue symptoms", "Typhoid"),
    ("typhoid symptoms persistent high temp and thakaan", "Typhoid"),
    ("bukhar jo hafte se chal raha hai pet mein dard signs", "Typhoid"),
    ("prolonged fever abdominal ache weakness typhoid", "Typhoid"),
    ("typhoid signs sustained high fever and stomach pain signs", "Typhoid"),
    ("muje bukhar hai aur pet kharab hai", "Typhoid"),
    ("ek hafte se bukhar aur pet mein dard kharab", "Typhoid"),
    ("pet kharab hai aur bahut kamzori lag rahi hai", "Typhoid"),
    ("typhoid symptoms stomach upset pet kharab fever", "Typhoid"),
    ("bukhar jhukaam aur pet kharab ek hafte se", "Typhoid"),
    ("sustained fever with pet kharab and jhukaam", "Typhoid"),
    ("long fever stomach pain and cold symptoms", "Typhoid"),



    # VIRAL FEVER - 50 samples
    ("high fever body ache headache fatigue weakness muscle pain", "Viral Fever"),
    ("fever chills sore throat cough runny nose body ache", "Viral Fever"),
    ("sudden onset high fever fatigue muscle pain headache", "Viral Fever"),
    ("bukhar sharir dard sar dard thakaan kamzori", "Viral Fever"),
    ("fever headache body ache weakness lethargy malaise", "Viral Fever"),
    ("high temp chills body ache cough sore throat fatigue", "Viral Fever"),
    ("viral infection fever headache body pain weakness", "Viral Fever"),
    ("bukhar sar dard thakaan sharir mein dard", "Viral Fever"),
    ("fever chills muscle ache headache fatigue", "Viral Fever"),
    ("tez bukhar sar dard thakaan kamzori mahsoos ho rahi hai", "Viral Fever"),
    ("high fever with runny nose and body ache", "Viral Fever"),
    ("bukhar thakaan aur sharir mein dard viral infection", "Viral Fever"),
    ("fever headache cough and weakness symptoms", "Viral Fever"),
    ("viral fever signs high temp and body pain", "Viral Fever"),
    ("bukhar hai aur sharir toot raha hai thakaan", "Viral Fever"),
    ("high fever chills and fatigue for two days", "Viral Fever"),
    ("fever headache and muscle ache viral", "Viral Fever"),
    ("bukhar sar dard aur kamzori ki shikayat", "Viral Fever"),
    ("viral fever symptoms high temperature and thakaan", "Viral Fever"),
    ("tez bukhar aur sharir mein dard viral", "Viral Fever"),
    ("high temp chills body ache weakness", "Viral Fever"),
    ("bukhar thakaan sharir mein dard", "Viral Fever"),
    ("fever headache body ache and cough", "Viral Fever"),
    ("viral infection high fever and weakness", "Viral Fever"),
    ("bukhar sar dard thakaan sharir dard", "Viral Fever"),
    ("high fever chills and muscle pain", "Viral Fever"),
    ("fever headache and fatigue symptoms", "Viral Fever"),
    ("bukhar thakaan aur kamzori viral", "Viral Fever"),
    ("viral fever signs high temp and body ache", "Viral Fever"),
    ("tez bukhar sharir mein dard aur thakaan", "Viral Fever"),
    ("high fever body ache and weakness", "Viral Fever"),
    ("bukhar sar dard thakaan kamzori", "Viral Fever"),
    ("fever chills muscle ache and fatigue", "Viral Fever"),
    ("viral infection high fever weakness", "Viral Fever"),
    ("bukhar thakaan sharir dard sar dard", "Viral Fever"),
    ("high fever chills body pain fatigue", "Viral Fever"),
    ("fever headache weakness lethargy", "Viral Fever"),
    ("bukhar sar dard thakaan kamzori mahsoos", "Viral Fever"),
    ("viral fever symptoms high temperature", "Viral Fever"),
    ("tez bukhar aur sharir mein dard", "Viral Fever"),
    ("high temp chills body ache fatigue", "Viral Fever"),
    ("bukhar thakaan sharir mein dard weakness", "Viral Fever"),
    ("fever headache body ache cough signs", "Viral Fever"),
    ("viral infection high fever thakaan", "Viral Fever"),
    ("bukhar sar dard thakaan sharir toot raha hai", "Viral Fever"),
    ("high fever chills and muscle ache", "Viral Fever"),
    ("fever headache and fatigue viral", "Viral Fever"),
    ("bukhar thakaan aur kamzori signs", "Viral Fever"),
    ("viral fever signs high temp body ache", "Viral Fever"),
    ("tez bukhar sharir mein dard thakaan signs", "Viral Fever"),
    ("muje jhukaam hai aur sharir dard", "Viral Fever"),
    ("sardi jhukaam aur halka bukhar thakaan", "Viral Fever"),
    ("jhukaam naak behna aur sar dard", "Viral Fever"),
    ("cough cold and mild fever jhukaam", "Viral Fever"),
    ("muje jhukaam hai aur thoda pet kharab bhi", "Viral Fever"),
    ("sardi jhukaam bukhar aur pet mein gadbad", "Viral Fever"),
    ("jhukaam with mild stomach upset", "Viral Fever"),



    # MALARIA - 50 samples
    ("high fever chills sweating headache muscle pain shivering", "Malaria"),
    ("fever shaking chills nausea vomiting fatigue body ache", "Malaria"),
    ("periodic fever every 2 days chills sweating headache", "Malaria"),
    ("bukhar kaanpna paseena sar dard ulti", "Malaria"),
    ("fever cycles rigors profuse sweating pallor splenomegaly", "Malaria"),
    ("bouts chills followed fever nausea muscle aches", "Malaria"),
    ("high fever cold stage chills hot stage sweating anemia", "Malaria"),
    ("intermittent fever shivers sweating episodes fatigue headache", "Malaria"),
    ("cyclical fever chills rigors sweating extreme weakness", "Malaria"),
    ("fever every alternate day chills sweating headache muscle pain", "Malaria"),
    ("bukhar thanda lagta hai paseena aata hai sar dard", "Malaria"),
    ("shivering followed fever sweating headache body ache weakness", "Malaria"),
    ("plasmodium fever chills rigors sweating pallor spleen", "Malaria"),
    ("fever cycles 48 hours shivering sweating fatigue", "Malaria"),
    ("recurrent fever chills nausea vomiting pallor jaundice", "Malaria"),
    ("high fever kaanpna sardarad ulti kamzori", "Malaria"),
    ("sudden fever chills sweating fatigue anemia enlarged spleen", "Malaria"),
    ("periodic fever rigors profuse sweating headache body ache", "Malaria"),
    ("intermittent high fever chills sweating muscle pain weakness", "Malaria"),
    ("bukhar thanda kaanpna paseena kamzori bhook nahi", "Malaria"),
    ("high fever with chills every second day sweating weakness", "Malaria"),
    ("thand lag kar bukhar ana aur thakaan malaria ki shikayat", "Malaria"),
    ("shivering fever headache and profuse sweating cycles", "Malaria"),
    ("malaria symptoms chills high temp headache and vomiting", "Malaria"),
    ("bukhar thanda lagta hai aur phir paseena aata hai", "Malaria"),
    ("intermittent high fever chills rigors and extreme weakness", "Malaria"),
    ("malaria fever pattern chills sweating headache body ache", "Malaria"),
    ("thand ke sath bukhar aur kamzori malaria signs", "Malaria"),
    ("high fever with severe shivering every other day", "Malaria"),
    ("malaria infection chills fever sweating and headache", "Malaria"),
    ("bukhar thand ke sath aur thakaan kamzori", "Malaria"),
    ("shivering fever episodes sweating and muscle pain", "Malaria"),
    ("malaria symptoms chills high fever nausea headache", "Malaria"),
    ("thand lag kar tez bukhar aur paseena ana", "Malaria"),
    ("periodic fever chills sweating and anemia signs", "Malaria"),
    ("bukhar thanda aur kaanpna thakaan kamzori", "Malaria"),
    ("malaria fever chills rigors sweating and fatigue", "Malaria"),
    ("thand lag kar bukhar ana malaria ki nishani", "Malaria"),
    ("high fever chills sweating headache body ache", "Malaria"),
    ("bukhar thand ke sath thakaan aur kamzori", "Malaria"),
    ("shivering followed by high fever and sweating", "Malaria"),
    ("malaria symptoms fever chills and body ache", "Malaria"),
    ("thand lag kar bukhar aur sar dard kamzori", "Malaria"),
    ("periodic fever chills sweating headache weakness", "Malaria"),
    ("bukhar thanda lagta hai aur paseena aata hai", "Malaria"),
    ("malaria signs high fever shivering and headache", "Malaria"),
    ("thand ke sath tez bukhar aur thakaan", "Malaria"),
    ("intermittent fever chills sweating body ache", "Malaria"),
    ("bukhar thand aur kaanpna malaria symptoms", "Malaria"),
    ("shivering fever headache sweating and weakness", "Malaria"),

    # DENGUE - 50 samples
    ("high fever severe headache pain behind eyes joint pain rash", "Dengue"),
    ("sudden high fever muscle pain skin rash nausea fatigue", "Dengue"),
    ("fever eye pain bone pain low platelet bleeding gums", "Dengue"),
    ("bukhar haddi dard aankhon mein dard skin rash kamzori", "Dengue"),
    ("high fever hemorrhagic rash platelet drop nosebleed vomiting", "Dengue"),
    ("severe joint pain high fever rash behind eyes pain", "Dengue"),
    ("dengue symptoms high fever body ache skin rash", "Dengue"),
    ("haddi tod bukhar joints mein dard aur laal daane", "Dengue"),
    ("breakbone fever high temp joint pain eye socket pain", "Dengue"),
    ("dengue fever rash platelet count low bleeding signs", "Dengue"),
    ("aankhon ke piche dard tez bukhar aur joints mein dard", "Dengue"),
    ("high fever severe body ache skin rash and nausea", "Dengue"),
    ("dengue signs high temp muscle pain joint pain", "Dengue"),
    ("sharir mein bahut dard tez bukhar aur laal chakte", "Dengue"),
    ("severe headache eye pain joint pain high fever", "Dengue"),
    ("dengue symptoms rash fever bone pain headache", "Dengue"),
    ("tez bukhar joints mein dard aur aankhon mein jalan", "Dengue"),
    ("high fever with skin rash and severe muscle pain", "Dengue"),
    ("dengue fever bone pain eye pain high temperature", "Dengue"),
    ("haddi tod bukhar tez fever aur joints pain", "Dengue"),
    ("sudden high fever severe headache and joint pain", "Dengue"),
    ("dengue rash high fever eye pain and nausea", "Dengue"),
    ("tez bukhar aur sharir mein bahut dard dengue", "Dengue"),
    ("high fever severe joint pain and low platelet signs", "Dengue"),
    ("dengue symptoms eye pain rash fever muscle ache", "Dengue"),
    ("joints mein tez dard bukhar aur laal daane", "Dengue"),
    ("breakbone fever signs high temp joint pain rash", "Dengue"),
    ("dengue fever high temperature eye pain body ache", "Dengue"),
    ("haddi mein dard tez bukhar aur skin rash", "Dengue"),
    ("severe dengue high fever bleeding signs rash", "Dengue"),
    ("dengue rash fever eye pain and joint pain", "Dengue"),
    ("tez bukhar aur joints mein dard dengue signs", "Dengue"),
    ("high fever severe muscle pain rash behind eyes", "Dengue"),
    ("dengue symptoms bone pain fever headache rash", "Dengue"),
    ("aankhon ke piche dard aur tez bukhar joints pain", "Dengue"),
    ("high fever severe joint pain rash and nausea", "Dengue"),
    ("dengue signs high temp bone pain muscle ache", "Dengue"),
    ("joints mein dard bukhar aur laal chakte dengue", "Dengue"),
    ("breakbone fever symptoms high fever joint pain", "Dengue"),
    ("dengue fever rash eye pain and severe body ache", "Dengue"),
    ("tez bukhar joints pain aur aankhon mein dard", "Dengue"),
    ("high fever with skin rash and muscle pain dengue", "Dengue"),
    ("dengue symptoms eye pain bone pain fever rash", "Dengue"),
    ("haddi tod bukhar tez temp aur joints mein dard", "Dengue"),
    ("sudden high fever rash eye pain and nausea", "Dengue"),
    ("dengue signs fever joint pain muscle ache", "Dengue"),
    ("joints mein dard bukhar aur laal daane dengue", "Dengue"),
    ("high fever severe headache eye pain rash", "Dengue"),
    ("dengue symptoms bone pain fever and body ache", "Dengue"),
    ("tez bukhar joints pain aur skin rash dengue", "Dengue"),
    ("severe joint pain fever skin rash extreme fatigue no appetite", "Dengue"),
    ("break bone fever headache retro orbital pain maculopapular rash", "Dengue"),
    ("fever muscle joint ache mild bleeding petechiae skin", "Dengue"),
    ("sudden high fever severe headache eye pain joint pain rash", "Dengue"),
    ("fever rash platelet low bleeding tendency body pain", "Dengue"),
    ("haddi dard aankhon ke peeche dard bukhar rash kamzori", "Dengue"),
    ("severe myalgia arthralgia fever rash thrombocytopenia", "Dengue"),
    ("high fever headache behind eyes pain rash on body weakness", "Dengue"),
    ("dengue rash fever platelet count low joint muscle pain", "Dengue"),
    ("sudden onset fever severe body pain rash nausea bleeding", "Dengue"),
    ("bukhar shareer mein dard aankhon mein dard rash kamzori", "Dengue"),
    ("fever 103 104 joint pain skin rash bleeding gums fatigue", "Dengue"),
    ("aedes fever rash thrombocytopenia headache eye pain", "Dengue"),
    ("high fever severe body ache rash petechiae nausea", "Dengue"),
    ("joint pain headache eye pain fever rash low platelets", "Dengue"),

    # TUBERCULOSIS - 20 samples
    ("persistent cough three weeks blood sputum weight loss night sweats", "Tuberculosis"),
    ("chronic cough fever weight loss fatigue chest pain night sweats", "Tuberculosis"),
    ("coughing blood prolonged cough breathing difficulty weakness sweating night", "Tuberculosis"),
    ("khansi khoon wajan kam bukhaar raat ko paseena", "Tuberculosis"),
    ("productive cough months hemoptysis low grade fever cachexia", "Tuberculosis"),
    ("cough more than 3 weeks loss weight anorexia fever lymph node", "Tuberculosis"),
    ("breathlessness chronic cough pleural effusion weight loss fatigue", "Tuberculosis"),
    ("pulmonary cough blood drenching night sweats fever evening wasting", "Tuberculosis"),
    ("cough more two months blood sputum weight loss fever sweating", "Tuberculosis"),
    ("prolonged cough hemoptysis night sweats weight loss weakness", "Tuberculosis"),
    ("khansi lambi kamzori wajan ghatna raat paseena", "Tuberculosis"),
    ("chronic productive cough blood tinged sputum fever weight loss", "Tuberculosis"),
    ("cough three months blood weight loss night fever sweating", "Tuberculosis"),
    ("persistent cough blood sputum weight loss low grade fever weakness", "Tuberculosis"),
    ("mahino se khansi khoon aana wajan kam raat ko bukhaar paseena", "Tuberculosis"),
    ("cough weeks blood fever chills night sweats cachexia", "Tuberculosis"),
    ("tb symptoms chronic cough hemoptysis weight loss night sweats", "Tuberculosis"),
    ("prolonged cough blood tinged sputum anorexia weight loss", "Tuberculosis"),
    ("khansi khoon aana raat ko paseena kamzori bhook nahi", "Tuberculosis"),
    ("chronic dry cough blood sputum weight loss evening fever", "Tuberculosis"),

    # CHOLERA - 18 samples
    ("severe watery diarrhea vomiting dehydration muscle cramps weakness", "Cholera"),
    ("rice water stools profuse diarrhea vomiting extreme thirst low bp", "Cholera"),
    ("sudden watery stool nausea vomiting dehydrated sunken eyes", "Cholera"),
    ("pani jaisi potty ulti pyas kamzori dehydration", "Cholera"),
    ("profuse diarrhea rice water rapid dehydration muscle cramps low urine", "Cholera"),
    ("acute watery diarrhea vomiting electrolyte loss shock extreme weakness", "Cholera"),
    ("severe loose watery stool vomiting dehydration cramps weakness", "Cholera"),
    ("profuse watery diarrhea no blood vomiting thirst weakness", "Cholera"),
    ("rice water diarrhea vomiting dehydration cramps weakness", "Cholera"),
    ("pani jaisi daast ulti pyas bahut zyada kamzori", "Cholera"),
    ("watery stool sudden dehydration vomiting sunken eyes cramping", "Cholera"),
    ("copious watery diarrhea vomiting leg cramps dehydration shock", "Cholera"),
    ("severe diarrhea no blood rice water stool vomiting dehydration", "Cholera"),
    ("vibrio cholera profuse diarrhea electrolyte imbalance dehydration", "Cholera"),
    ("sudden watery stool vomiting thirst weakness dehydrated", "Cholera"),
    ("bahut pani jaisi potty ulti dehydration kamzori", "Cholera"),
    ("acute diarrhea watery no fever vomiting cramps thirst", "Cholera"),
    ("profuse watery diarrhea rice water appearance vomiting dehydration", "Cholera"),

    # VIRAL FEVER - 20 samples
    ("mild fever runny nose sore throat cough body ache fatigue", "Viral Fever"),
    ("fever cold blocked nose throat pain headache tiredness", "Viral Fever"),
    ("low grade fever sneezing watery eyes weakness mild headache", "Viral Fever"),
    ("bukhar naak bana gale mein dard thakaan sar dard", "Viral Fever"),
    ("fever body pain chills runny nose loss appetite", "Viral Fever"),
    ("mild temperature cough sore throat fatigue joint ache", "Viral Fever"),
    ("fever 100 101 cold symptoms headache tiredness", "Viral Fever"),
    ("influenza fever myalgia rhinitis pharyngitis malaise", "Viral Fever"),
    ("low grade fever cold sneezing headache body ache weakness", "Viral Fever"),
    ("fever sore throat runny nose cough fatigue aches", "Viral Fever"),
    ("bukhar zukaam gale mein kharash thakaan sar dard", "Viral Fever"),
    ("mild fever cold nose blocked throat pain weakness", "Viral Fever"),
    ("seasonal fever cold cough headache body pain tiredness", "Viral Fever"),
    ("low fever sneezing runny nose headache fatigue", "Viral Fever"),
    ("bukhar naak beh rahi hai gala dukh raha hai", "Viral Fever"),
    ("mild temperature sore throat cough headache fatigue weakness", "Viral Fever"),
    ("fever cough cold body ache headache loss appetite", "Viral Fever"),
    ("thoda sa bukhar zukaam khansi thakaan sar dard", "Viral Fever"),
    ("mild fever runny nose throat pain fatigue body aches", "Viral Fever"),
    ("low grade fever cold symptoms cough headache weakness", "Viral Fever"),

    # PNEUMONIA - 20 samples
    ("high fever chest pain difficulty breathing cough phlegm chills", "Pneumonia"),
    ("breathlessness chest tightness fever productive cough fatigue", "Pneumonia"),
    ("severe cough breathing difficulty high temperature chest pain sweating", "Pneumonia"),
    ("saans lene mein takleef seene mein dard bukhaar khansi", "Pneumonia"),
    ("lobar pneumonia fever pleuritic chest pain cough sputum tachycardia", "Pneumonia"),
    ("consolidation lung high fever rusty sputum dyspnea rigors", "Pneumonia"),
    ("chest infection fever breathlessness crackles reduced breath sounds", "Pneumonia"),
    ("fever high cough green yellow sputum ribs hurt breathing", "Pneumonia"),
    ("high fever chest pain shortness breath productive cough shivering", "Pneumonia"),
    ("breathlessness chest tightness high fever cough with mucus weakness", "Pneumonia"),
    ("seene mein dard saans ki takleef bukhaar balgam khansi", "Pneumonia"),
    ("severe chest infection high fever difficulty breathing cough", "Pneumonia"),
    ("lung infection fever chest pain breathlessness mucus cough", "Pneumonia"),
    ("high temperature chest pain breathing problem cough phlegm", "Pneumonia"),
    ("saans nahi aa rahi seene mein dard bukhaar khansi balgam", "Pneumonia"),
    ("fever chills chest pain productive cough dyspnea fatigue", "Pneumonia"),
    ("chest pain breathing difficulty high fever cough mucus sweating", "Pneumonia"),
    ("pneumonia fever chest tightness breathlessness sputum cough", "Pneumonia"),
    ("lung infection breathing hard chest pain fever cough", "Pneumonia"),
    ("seene mein dard saans fulna bukhaar balgam wali khansi", "Pneumonia"),

    # ANAEMIA - 18 samples
    ("weakness fatigue pale skin dizziness shortness breath exertion", "Anaemia"),
    ("extreme tiredness paleness breathlessness cold hands feet headache", "Anaemia"),
    ("low energy pale conjunctiva weakness fainting rapid heartbeat", "Anaemia"),
    ("kamzori chakkar thakaan pale rang saans fulna", "Anaemia"),
    ("haemoglobin low fatigue pallor dyspnea exertion palpitations", "Anaemia"),
    ("iron deficiency tiredness brittle nails pale face weakness", "Anaemia"),
    ("weakness dizziness paleness tiredness breathlessness on effort", "Anaemia"),
    ("fatigue pale conjunctiva weakness breathlessness fast heartbeat", "Anaemia"),
    ("kamzori thakaan chakkar aana pale skin", "Anaemia"),
    ("extreme weakness pale face tiredness breathlessness cold extremities", "Anaemia"),
    ("low hemoglobin weakness fatigue pallor breathlessness palpitation", "Anaemia"),
    ("bahut kamzori thakaan chakkar khoon ki kami", "Anaemia"),
    ("fatigue pallor breathlessness on exertion cold hands weakness", "Anaemia"),
    ("weakness tiredness dizziness pale skin fast heart rate", "Anaemia"),
    ("khoon ki kami kamzori thakaan saans fulna chakkar", "Anaemia"),
    ("anaemia weakness pale conjunctiva fatigue dyspnea palpitations", "Anaemia"),
    ("iron deficient weakness tiredness pale face cold hands breathless", "Anaemia"),
    ("thakaan kamzori chakkar aana saans ki kami", "Anaemia"),

    # JAUNDICE - 18 samples
    ("yellow skin yellow eyes dark urine fatigue nausea abdominal pain", "Jaundice"),
    ("yellowing eyes skin itching pale stools vomiting weakness", "Jaundice"),
    ("jaundice dark brown urine clay colored stool nausea liver pain", "Jaundice"),
    ("aankhein peeli chamdi peeli peshab peela kamzori bukhar", "Jaundice"),
    ("icteric hepatomegaly anorexia bilirubin high pruritus", "Jaundice"),
    ("hepatitis yellow discoloration right upper quadrant pain malaise", "Jaundice"),
    ("yellow eyes skin dark urine fatigue stomach pain nausea", "Jaundice"),
    ("yellowing of eyes body weakness dark urine nausea vomiting", "Jaundice"),
    ("aankhein aur chamdi peeli ho gayi peshab gehra", "Jaundice"),
    ("liver problem yellow eyes dark urine fatigue abdominal pain", "Jaundice"),
    ("icteric yellow eyes skin pale stool dark urine fatigue", "Jaundice"),
    ("peeli aankhein peela peshab pet mein dard thakaan", "Jaundice"),
    ("hepatitis yellow skin eyes dark urine nausea weakness fever", "Jaundice"),
    ("bilirubin elevated jaundice itching dark urine fatigue", "Jaundice"),
    ("aankhein peeli twacha peeli peshab peela nausea weakness", "Jaundice"),
    ("yellow sclera yellow skin clay stool dark urine nausea", "Jaundice"),
    ("jaundice itching fatigue yellow eyes dark urine pale stool", "Jaundice"),
    ("aankhein peeli peshab gehra rang pet dard kamzori", "Jaundice"),

    # DYSENTERY - 18 samples
    ("diarrhea blood mucus stomach cramps fever vomiting", "Dysentery"),
    ("bloody stool painful diarrhea abdominal cramps nausea fever", "Dysentery"),
    ("loose stool blood tenesmus abdominal pain weakness", "Dysentery"),
    ("blood pichad potty pet mein dard bukhar ulti", "Dysentery"),
    ("amoebic dysentery intermittent diarrhea blood mucus colicky pain", "Dysentery"),
    ("bacillary dysentery fever cramps frequent bloody stools dehydration", "Dysentery"),
    ("bloody diarrhea cramps fever nausea weakness dehydration", "Dysentery"),
    ("diarrhea with blood stomach pain fever nausea weakness", "Dysentery"),
    ("blood mucus stool abdominal pain fever dehydration", "Dysentery"),
    ("khoon aur balgam potty pet mein dard bukhar ulti", "Dysentery"),
    ("frequent bloody stool cramping fever weakness dehydration", "Dysentery"),
    ("blood stool diarrhea stomach cramps fever vomiting weakness", "Dysentery"),
    ("khoon wali potty pet mein dard thakaan bukhar", "Dysentery"),
    ("dysentery bloody loose motion stomach cramps fever", "Dysentery"),
    ("blood in stool abdominal cramping fever nausea weakness", "Dysentery"),
    ("tenesmus bloody diarrhea cramps fever weakness dehydration", "Dysentery"),
    ("khoon ki potty pet dard bukhar kamzori ulti", "Dysentery"),
    ("mucus blood stool stomach pain fever vomiting fatigue", "Dysentery"),

    # CHICKENPOX - 18 samples
    ("itchy blisters all over body fever red spots vesicles", "Chickenpox"),
    ("blisters rash fever itching vesicles face body arms", "Chickenpox"),
    ("pox marks fluid filled blisters fever itching loss appetite", "Chickenpox"),
    ("chechak khujali chchale bukhar daane poore badan pe", "Chickenpox"),
    ("varicella pruritic vesicular rash low grade fever malaise", "Chickenpox"),
    ("itchy rash blisters fever all over body", "Chickenpox"),
    ("fluid blisters body fever itching loss appetite", "Chickenpox"),
    ("pox vesicles fever itching spreading rash", "Chickenpox"),
    ("daane khujali chchale bukhar poore badan mein", "Chickenpox"),
    ("chickenpox blisters fever itching rash all over", "Chickenpox"),
    ("itchy spots becoming blisters mild fever weakness", "Chickenpox"),
    ("vesicular rash fever itching spreading face body", "Chickenpox"),
    ("chechak chchale khujali thoda bukhar", "Chickenpox"),
    ("pox rash blisters fever itching body arms face", "Chickenpox"),
    ("fluid filled spots fever itching spreading rash", "Chickenpox"),
    ("daane nikle hain poore badan mein khujali bukhar", "Chickenpox"),
    ("itchy blisters fever weakness loss of appetite", "Chickenpox"),
    ("vesicles body face arms fever itching rash", "Chickenpox"),

    # MEASLES - 18 samples
    ("high fever cough runny nose red eyes skin rash starting face", "Measles"),
    ("rash spreading face body fever cough red watery eyes", "Measles"),
    ("koplik spots maculopapular rash fever coryza conjunctivitis", "Measles"),
    ("khasra daane bukhaar aankhein laal khansi naak bana", "Measles"),
    ("rubeola high fever prodrome cough rash spreading downward photophobia", "Measles"),
    ("rash starting face spreading body fever cough red eyes", "Measles"),
    ("fever rash spreading red eyes runny nose cough weakness", "Measles"),
    ("measles rash face body fever cough watery eyes", "Measles"),
    ("khasra bukhar daane aankhein laal khansi", "Measles"),
    ("maculopapular rash fever red eyes cough runny nose", "Measles"),
    ("rash on face spreading down body high fever cough", "Measles"),
    ("fever red eyes cough rash starting on face", "Measles"),
    ("daane munh se shuru poore badan mein bukhar aankhein laal", "Measles"),
    ("measles koplik spots rash fever cough photophobia", "Measles"),
    ("red eyes runny nose cough rash body fever weakness", "Measles"),
    ("khasra daane munh se shuru bukhar aankhen laal naak bana", "Measles"),
    ("high fever rash starting face spreading body watery eyes cough", "Measles"),
    ("morbilli rash fever cough coryza conjunctivitis koplik spots", "Measles"),
    # HEATSTROKE - 15 samples
    ("very high body temperature confusion dizziness no sweating hot dry skin collapse", "Heatstroke"),
    ("body temperature 40 celsius confusion disorientation fainting hot skin", "Heatstroke"),
    ("garmi mein behosh hona tez bukhaar paseena nahi aana confusion", "Heatstroke"),
    ("extreme heat exposure fever above 104 confusion loss consciousness dry skin", "Heatstroke"),
    ("sun stroke no sweating very high temperature fainting", "Heatstroke"),
    ("heat exhaustion confusion dizziness nausea high body temperature dry skin", "Heatstroke"),
    ("body overheating red hot dry skin confusion rapid pulse collapse", "Heatstroke"),
    ("garmi se behoshi tez bukhaar paseena nahi sar mein dard", "Heatstroke"),
    ("hyperthermia confusion rapid heartbeat very hot skin no perspiration weakness", "Heatstroke"),
    ("heat stroke 40 celsius body confusion disorientation dry skin rapid heart", "Heatstroke"),
    ("sun exposure high fever no sweat confusion fainting headache", "Heatstroke"),
    ("garmi mein sir ghoomna bukhaar hot skin behosh", "Heatstroke"),
    ("body temperature extremely high confusion dry hot skin collapsed", "Heatstroke"),
    ("severe heat exposure above 40 celsius no sweating confusion collapse", "Heatstroke"),
    ("dhoop mein rehna hot dry skin tez bukhaar behosh", "Heatstroke"),

    # SNAKEBITE - 15 samples
    ("snake bite swelling pain fang marks dizziness nausea vomiting", "Snakebite"),
    ("saanp ne kata soojan dard behoshi ulti chakkar", "Snakebite"),
    ("bite marks swelling limb pain numbness vomiting blurred vision", "Snakebite"),
    ("snakebite fang marks swelling spreading pain paralysis breathing difficulty", "Snakebite"),
    ("snake bite paralysis numbness swelling drooling convulsions", "Snakebite"),
    ("saanp ke daanth ka nishaan soojan dard numbness", "Snakebite"),
    ("puncture wounds swelling limb pain nausea vomiting breathing problem", "Snakebite"),
    ("snake envenomation swelling necrosis pain vomiting blurred vision weakness", "Snakebite"),
    ("bite leg arm soojan zyada dard ulti behoshi", "Snakebite"),
    ("snake bite two fang marks swelling spreading rapid heartbeat dizziness", "Snakebite"),
    ("venomous bite swelling numbing pain moving up limb drooling convulsion", "Snakebite"),
    ("saanp ne daanth maara soojan numb ho gaya dard ulti", "Snakebite"),
    ("fang marks pain spreading swelling bleeding wound dizziness", "Snakebite"),
    ("snake bite pain numbness paralysis vomiting breathing difficulty", "Snakebite"),
    ("saanp kata hai soojan dard behoshi saans lene mein takleef", "Snakebite"),

    # ACUTE RESPIRATORY INFECTION - 15 samples
    ("fever cough breathing difficulty sore throat body ache fatigue loss smell", "Acute Respiratory Infection"),
    ("high fever dry cough breathlessness fatigue loss taste smell", "Acute Respiratory Infection"),
    ("cough fever body pain headache weakness breathing problem", "Acute Respiratory Infection"),
    ("bukhar khansi saans ki takleef thakaan nasam mein dard", "Acute Respiratory Infection"),
    ("sore throat fever runny nose cough fatigue body pain breathing difficulty", "Acute Respiratory Infection"),
    ("high fever cough shortness breath weakness loss appetite", "Acute Respiratory Infection"),
    ("fever persistent dry cough fatigue difficulty breathing", "Acute Respiratory Infection"),
    ("bukhar khansi thakaan saans nahi aa rahi khana nahi khana", "Acute Respiratory Infection"),
    ("respiratory infection cough fever breathing problem extreme fatigue", "Acute Respiratory Infection"),
    ("cough with fever difficulty breathing weakness body ache headache", "Acute Respiratory Infection"),
    ("viral respiratory fever cough breathlessness loss of smell and taste", "Acute Respiratory Infection"),
    ("tez bukhar sukhi khansi thakaan saans ki takleef", "Acute Respiratory Infection"),
    ("fever cough shortness breath loss smell body weakness", "Acute Respiratory Infection"),
    ("high fever cough sore throat fatigue diarrhea body ache", "Acute Respiratory Infection"),
    ("bukhar khansi jism mein dard saans ki takleef kamzori", "Acute Respiratory Infection"),
    ("kaichal thalaivaali vayiru vali pasiyilla kamayosam", "Typhoid"),
    ("neetitta kaichal vayiru vali thalarchi", "Typhoid"),
    ("oru vaaram kaichal thalaivaali vayiru thalarchi", "Typhoid"),
    ("jvaaram naale irukku thalaivaali pasi illai kamayosam", "Typhoid"),
    ("nirantara kaichal vayiru kuzhambu thalaivaali kamayosam", "Typhoid"),
    ("kaichal nirungal viyarvai thalaivaali thalarchi malaria", "Malaria"),
    ("kaichal oer irandhu naal vidum nirungal viyarvai malaria", "Malaria"),
    ("nirungal pinnadi kaichal viyarvai thalaivaali malaria", "Malaria"),
    ("maari kaichal nirungal viyarvai kamayosam malaria", "Malaria"),
    ("idaiveli kaichal nirungal viyarvai thalarchi malaria", "Malaria"),
    ("dengue kaichal kal vaali thalaivaali kan pinna vaali", "Dengue"),
    ("dengue kaichal jaathi kuraival kamayosam thalarchi", "Dengue"),
    ("koorai kaichal teri jaathi kurai thalarchi kal vaali", "Dengue"),
    ("kaichal teri kan vaali kal kal vaali kamayosam dengue", "Dengue"),
    ("kaichal talai pinna kal vaali teri kan vaali dengue", "Dengue"),
    ("iraimookku irumal iraththam thookam izhapu uzhaippu", "Tuberculosis"),
    ("neetitta irumal iraththam vanthu thalarchi uzhaippu", "Tuberculosis"),
    ("irandu maatha irumal iraththam kaichal thookam viyarvai", "Tuberculosis"),
    ("iru maasa irumal uzhaippu kaichal iravil viyarvai", "Tuberculosis"),
    ("neettam irumal iru maasam kaichal thookam izhapu", "Tuberculosis"),
    ("veytham therindhu vanthu vomi valandhu kaichal thakam", "Cholera"),
    ("arisi thanni pola moonru valandhu kamayosam thakam", "Cholera"),
    ("kaichal illama veytham thanni pola vanthu thalarchi", "Cholera"),
    ("thanni peyar vomi thaakam thalarchi kamayosam cholera", "Cholera"),
    ("rice water stool vomi thakam thalarchi cholera", "Cholera"),
    ("sirukaichal thalaivaali kal vaali thalarchi sali irumal", "Viral Fever"),
    ("kaichal jalanam ookkam irumal thalaivaali sali", "Viral Fever"),
    ("sirukaichal kannai ookkam mukku ozukkam thalarchi", "Viral Fever"),
    ("thalarchi thalaivaali kaichal sali irumal kal vaali", "Viral Fever"),
    ("mild kaichal mukkul ozukkam sali thalarchi ookkam", "Viral Fever"),
    ("kaichal maarbu vaali moochu thittam irumal balgam", "Pneumonia"),
    ("maarbil veytham kaichal moochu thittam balgam irumal", "Pneumonia"),
    ("moochu thittam maarbu vaali kaichal balgam irumal", "Pneumonia"),
    ("thalarchi maarbu vaali kaichal balgam irumal svaasam", "Pneumonia"),
    ("svaasam thittam maarbu vaali kaichal irumal balgam", "Pneumonia"),
    ("thalarchi palor chakravakam ookkamilla moochu thittam ratham", "Anaemia"),
    ("rattha kammi thalarchi ookkamilla palor moochu thittam", "Anaemia"),
    ("thalarchi rattha kammi sali palor chakravakam", "Anaemia"),
    ("ookkamilla thalarchi pazhuthu moochu thittam ratham", "Anaemia"),
    ("irattha kuraivu thalarchi chakravakam moochu thittam", "Anaemia"),
    ("kan peela kamayosam vayiru vaali kaichal siru neer peela", "Jaundice"),
    ("thol peela siru neer peela thalarchi kaichal vayiru", "Jaundice"),
    ("kan peela iruppam kamayosam vayiru vaali thalarchi", "Jaundice"),
    ("thol peela thalarchi siru neer peela kaichal vomii", "Jaundice"),
    ("jaundice kan peela thol peela siru neer peela kamayosam", "Jaundice"),
    ("iraththa moonru vayiru vaali kaichal vomi thalarchi", "Dysentery"),
    ("iraththa peyar vayiru vaali kaichal thalarchi", "Dysentery"),
    ("balgam moonru vayiru vaali kaichal thalarchi vomii", "Dysentery"),
    ("iraththa peyar thalarchi kaichal vayiru kuzhambu", "Dysentery"),
    ("bloody moonru vayiru kaichal kamayosam vomii", "Dysentery"),
    ("pet kharab hai aur dast ho rahe hain", "Dysentery"),
    ("loose motion pet kharab aur marode", "Dysentery"),
    ("pet mein dard aur baar baar dast jana", "Dysentery"),
    ("stomach upset with loose motions pet kharab", "Dysentery"),

    ("sarumpu muzhuthu kaichal teri tholarchi", "Chickenpox"),
    ("sarumpu kaichal teri muzhuthu balam tholarchi", "Chickenpox"),
    ("teri kaichal sarumpu muzhuthu kamayosam", "Chickenpox"),
    ("kaichal sarumpu neerppai muzhuthu tholarchi", "Chickenpox"),
    ("chickenpox sarumpu kaichal teri muzhuthu balam", "Chickenpox"),
    ("kaichal irumal kan sivappu teri vanthu measles", "Measles"),
    ("teri mukkal thodangi muzhuthu patsai thalarchi irumal", "Measles"),
    ("kaichal irumal teri mukkal sivappu kan", "Measles"),
    ("koplik tholi teri kaichal irumal sivappu measles", "Measles"),
    ("high fever teri mukkal kaichal kan sivappu sali", "Measles"),
    ("maikkumidam kaichal viyarvai illai thalarchi heatstroke", "Heatstroke"),
    ("veyilil irukka maayakam uchcha kaichal viyarvai illai", "Heatstroke"),
    ("veyil kaichal viyarvai illai maayakam thalarchi", "Heatstroke"),
    ("uchcha veppam kaichal kuzhappam thalarchi maayakam", "Heatstroke"),
    ("heatstroke viyarvai illai uchcha veppam maayakam", "Heatstroke"),
    ("pambu kadichathu veekam vaali maayakam vomi snakebite", "Snakebite"),
    ("pambu theidum veekam kal vaali moochu thittam", "Snakebite"),
    ("pambu kadichathu veekam vaali moochu thittam maayakam", "Snakebite"),
    ("pambu kadichathu vomi chakravakam veekam vaali", "Snakebite"),
    ("snakebite veekam vaali moochu thittam maayakam vomi", "Snakebite"),
    ("kaichal irumal moochu thittam thalarchi svaasam ari", "Acute Respiratory Infection"),
    ("thodam kaichal irumal moochu thittam thalarchi", "Acute Respiratory Infection"),
    ("kaichal irumal moochu thittam thalarchi kamayosam ari", "Acute Respiratory Infection"),
    ("viral kaichal irumal moochu thittam uchcha thalarchi", "Acute Respiratory Infection"),
    ("respiratory kaichal irumal svaasam thittam thalarchi", "Acute Respiratory Infection"),
    ("fever", "Viral Fever"),
    ("fever cough", "Viral Fever"),
    ("fever cough weakness", "Viral Fever"),
    ("fever cough headache", "Viral Fever"),
    ("fever headache weakness", "Typhoid"),
    ("fever headache vomiting", "Malaria"),
    # PNEUMONIA - 50 samples
    ("fever cough chest_pain breathing", "Pneumonia"),
    ("fever cough breathing weakness", "Pneumonia"),
    ("fever chest_pain breathing", "Pneumonia"),
    ("chest_pain breathing", "Pneumonia"),
    ("high fever severe cough with phlegm difficulty breathing", "Pneumonia"),
    ("seene mein dard khansi aur saans lene mein takleef", "Pneumonia"),
    ("pneumonia symptoms fever cough yellow mucus shortness of breath", "Pneumonia"),
    ("khansi mein balgam bukhar aur seene mein jalan", "Pneumonia"),
    ("productive cough high fever chest pain rapid breathing", "Pneumonia"),
    ("saans phulna tez khansi aur bukhar seene mein dard", "Pneumonia"),
    ("fever cough with green phlegm chest pain breathlessness", "Pneumonia"),
    ("balgam wali khansi bukhar aur saans lene mein dikkat", "Pneumonia"),
    ("severe pneumonia fever cough rapid pulse low oxygen", "Pneumonia"),
    ("khansi bukhar aur saans fulne ki shikayat", "Pneumonia"),
    ("chest infection high fever productive cough breathing pain", "Pneumonia"),
    ("seene mein dard aur tez khansi bukhar ke sath", "Pneumonia"),
    ("fever cough shortness of breath chest tightness", "Pneumonia"),
    ("khansi balgam aur saans lene mein bahut takleef", "Pneumonia"),
    ("pneumonia signs fever cough shivering chest pain", "Pneumonia"),
    ("bukhar khansi aur seene mein dard saans fulna", "Pneumonia"),
    ("bacterial pneumonia high fever cough yellow sputum", "Pneumonia"),
    ("viral pneumonia dry cough fever difficulty breathing", "Pneumonia"),
    ("saans lene mein dard khansi aur tez bukhar", "Pneumonia"),
    ("chest congestion fever cough difficulty in breathing", "Pneumonia"),
    ("seene mein jakadan khansi aur bukhar", "Pneumonia"),
    ("fever with cough and sharp chest pain while breathing", "Pneumonia"),
    ("tez khansi balgam ke sath aur saans fulna", "Pneumonia"),
    ("productive cough fever shortness of breath chest ache", "Pneumonia"),
    ("bukhar khansi aur seene mein jalan ki shikayat", "Pneumonia"),
    ("saans phulti hai khansi aati hai aur bukhar hai", "Pneumonia"),

    # TUBERCULOSIS (TB) - 50 samples
    ("fever cough bleeding", "Tuberculosis"),
    ("cough bleeding weakness", "Tuberculosis"),
    ("cough for months blood coming out night sweat weight loss", "Tuberculosis"),
    ("prolonged cough with blood loss of appetite evening fever night sweats", "Tuberculosis"),
    ("mahino se khansi khoon ata hai raat ko paseena aur wajan kam", "Tuberculosis"),
    ("hemoptysis night sweats cachexia prolonged cough weakness", "Tuberculosis"),
    ("khansi mein khoon raat ko paseena wajan ghatna bukhaar thakaan", "Tuberculosis"),
    ("chronic cough blood tinged weight loss sweating at night fever", "Tuberculosis"),
    ("productive cough blood fever only evenings weight loss sweating", "Tuberculosis"),
    ("long standing cough blood fever night sweats losing weight fatigue", "Tuberculosis"),
    ("tb symptoms cough with blood night sweats weight loss", "Tuberculosis"),
    ("purani khansi khoon ke sath raat ko paseena aur thakaan", "Tuberculosis"),
    ("chronic tb fever weight loss cough lasting 3 weeks", "Tuberculosis"),
    ("khansi jo theek nahi ho rahi khoon ana aur wajan kam", "Tuberculosis"),
    ("pulmonary tuberculosis cough blood hemoptysis night sweat", "Tuberculosis"),
    ("raat ko paseena ana bhook kam aur khansi mein khoon", "Tuberculosis"),
    ("tb infection fever cough with blood loss of weight", "Tuberculosis"),
    ("purani khansi balgam mein khoon aur sham ko bukhar", "Tuberculosis"),
    ("cough for long time blood in spit night sweats weakness", "Tuberculosis"),
    ("tb signs chronic cough weight loss evening fever", "Tuberculosis"),
    ("khansi mein khoon ana aur bahut kamzori mahsoos hona", "Tuberculosis"),
    ("weight loss chronic cough blood tinged sputum night sweats", "Tuberculosis"),
    ("mahino purani khansi khoon ke sath aur paseena", "Tuberculosis"),
    ("tb risk cough blood weight loss loss of appetite", "Tuberculosis"),
    ("khansi mein khoon aur sham ke waqt tez bukhar", "Tuberculosis"),
    ("chronic cough weight loss fatigue fever in evenings", "Tuberculosis"),
    ("tb symptoms blood in phlegm night sweat weight loss", "Tuberculosis"),
    ("khansi mein khoon ana aur wajan bahut kam ho gaya hai", "Tuberculosis"),
    ("prolonged cough weight loss night sweats fever tb", "Tuberculosis"),
    ("purani khansi khoon aur kamzori tb ki shikayat", "Tuberculosis"),

    # CHOLERA / DYSENTERY - 50 samples
    ("fever vomiting diarrhea weakness", "Cholera"),
    ("vomiting diarrhea weakness", "Cholera"),
    ("fever vomiting bleeding diarrhea", "Dysentery"),
    ("rice water stools severe dehydration vomiting muscle cramps", "Cholera"),
    ("pani jaisa dast ulti aur sharir mein paani ki kami", "Cholera"),
    ("bloody diarrhea with mucus stomach cramps and fever", "Dysentery"),
    ("khonni dast pet mein marode aur bukhar", "Dysentery"),
    ("cholera symptoms watery diarrhea vomiting dehydration", "Cholera"),
    ("dast aur ulti sharir mein bilkul jaan nahi paani kam", "Cholera"),
    ("dysentery signs blood in stool abdominal cramps fever", "Dysentery"),
    ("pet mein dard aur khoon wale dast dysentery", "Dysentery"),
    ("severe watery diarrhea vomiting and muscle cramps cholera", "Cholera"),
    ("dast mein khoon aur pet mein bahut marode", "Dysentery"),
    ("watery stools severe dehydration vomiting cholera", "Cholera"),
    ("ultiyan aur dast sharir mein paani ki kami kamzori", "Cholera"),
    ("bloody stool stomach pain fever dysentery", "Dysentery"),
    ("khoon wale dast aur pet mein dard dysentery", "Dysentery"),
    ("cholera risk watery diarrhea vomiting fatigue", "Cholera"),
    ("dast aur ulti sharir sukh gaya hai cholera", "Cholera"),
    ("dysentery symptoms blood in diarrhea stomach cramps", "Dysentery"),
    ("pet dard aur khoon ke sath dast dysentery", "Dysentery"),
    ("watery diarrhea severe dehydration cholera signs", "Cholera"),
    ("dast aur ulti se bura haal sharir mein paani nahi", "Cholera"),
    ("dysentery fever blood in stool abdominal pain", "Dysentery"),
    ("khooni dast aur pet mein dard ki shikayat", "Dysentery"),
    ("rice water diarrhea vomiting dehydration cholera", "Cholera"),
    ("ulti aur dast pani jaisa cholera infection", "Cholera"),
    ("dysentery signs bloody diarrhea stomach cramps", "Dysentery"),
    ("pet mein dard aur khoon wala dast dysentery", "Dysentery"),
    ("severe diarrhea vomiting dehydration cholera symptoms", "Cholera"),

    # CHILDHOOD DISEASES (Chickenpox/Measles) - 50 samples
    ("fever rash itching", "Chickenpox"),
    ("fever rash cough", "Measles"),
    ("red spots all over body with itching and fever", "Chickenpox"),
    ("sharir par daane khujli aur bukhar chickenpox", "Chickenpox"),
    ("measles rash high fever red eyes runny nose cough", "Measles"),
    ("daane chehre se shuru hokar badan par aur tez bukhar", "Measles"),
    ("chickenpox symptoms red itchy blisters fever headache", "Chickenpox"),
    ("sharir par paani wale daane aur bahut khujli", "Chickenpox"),
    ("measles symptoms red spots cough runny nose fever", "Measles"),
    ("khansi bukhar aur sharir par laal daane measles", "Measles"),
    ("itchy rash blisters all over body fever chickenpox", "Chickenpox"),
    ("sharir par daane khujli aur thakaan chickenpox", "Chickenpox"),
    ("measles signs red eyes cough high fever rash", "Measles"),
    ("laal aankhen khansi aur sharir par daane measles", "Measles"),
    ("chickenpox rash small blisters itchy fever", "Chickenpox"),
    ("sharir par khujli wale daane chickenpox", "Chickenpox"),
    ("measles fever cough red spots starting on face", "Measles"),
    ("chehre par daane jo badan par phail rahe hain measels", "Measles"),
    ("chickenpox symptoms itchy red spots fever", "Chickenpox"),
    ("sharir mein daane aur khujli ki shikayat", "Chickenpox"),
    ("measles risk fever cough red watery eyes rash", "Measles"),
    ("khansi bukhar aur laal daane measels ki nishani", "Measles"),
    ("itchy blisters fever headache chickenpox signs", "Chickenpox"),
    ("sharir par laal daane aur bahut khujli chickenpox", "Chickenpox"),
    ("measles high fever rash red eyes cough", "Measles"),
    ("tez bukhar aur sharir par laal daane measles", "Measles"),
    ("chickenpox rash blisters fever itching", "Chickenpox"),
    ("sharir par pani wale daane chickenpox", "Chickenpox"),
    ("measles symptoms cough fever red spots", "Measles"),
    ("laal daane bukhar aur khansi measles", "Measles"),
    ("khansi mein khoon raat ko paseena wajan ghatna bukhaar thakaan", "Tuberculosis"),
    ("chronic cough blood tinged weight loss sweating at night fever", "Tuberculosis"),
    ("productive cough blood fever only evenings weight loss sweating", "Tuberculosis"),
    ("long standing cough blood fever night sweats losing weight fatigue", "Tuberculosis"),
    ("rash starting on face spreading down to body with high fever cough", "Measles"),
    ("face rash spreading whole body fever cough watery red eyes measles", "Measles"),
    ("koplik spots white inside mouth fever rash spreads down measles", "Measles"),
    ("high fever rash begins face then neck then trunk cough red eyes", "Measles"),
    ("mukh ke andar daag phir pura badan mein daane bukhar aankhein laal", "Measles"),
    ("fever rash from hairline downward red eyes runny nose cough measles", "Measles"),
    ("maculopapular rash starting face ears high fever red eyes cough", "Measles"),
    ("daane pehle munh pe phir neeche bukhar aankhein laal naak bana", "Measles"),
    ("fever cough breathing difficulty throat pain body ache no smell taste", "Acute Respiratory Infection"),
    ("dry persistent cough high fever breathlessness difficulty breathing", "Acute Respiratory Infection"),
    ("saans ki takleef khansi bukhar seene mein tightness thakaan gandh nahi", "Acute Respiratory Infection"),
    ("severe cough fever difficulty breathing short of breath oxygen low", "Acute Respiratory Infection"),
    ("fever cough loss of smell and taste extreme fatigue respiratory", "Acute Respiratory Infection"),
    ("khansi saans ki takleef bukhar thakaan gandh na aana khana swad nahi", "Acute Respiratory Infection"),
    ("respiratory illness fever dry cough breathlessness weakness no taste", "Acute Respiratory Infection"),
    ("upper respiratory infection fever cough sore throat bodyache breathing", "Acute Respiratory Infection"),
    ("fever for exactly one week getting higher each day then constipation", "Typhoid"),
    ("step-ladder fever week constipation then diarrhea headache typhoid", "Typhoid"),
    ("ek hafte se bukhar roz thoda zyada hota hai pet mein dard bhook nahi", "Typhoid"),
    ("enteric fever one week abdomen tender slow heartbeat rose spots", "Typhoid"),
    ("continuous high fever one week stomach pain constipation headache weak", "Typhoid"),
    ("ek hafte bukhar badh raha hai pet phula hua bhook nahi hai kamzori", "Typhoid"),
    ("sustained week long fever slow pulse hepatosplenomegaly abdominal pain", "Typhoid"),
    ("fever day after day higher no appetite constipation bloated abdomen", "Typhoid"),
    # JAUNDICE (Peeliya) - 50 samples (Expanded)
    ("yellow skin yellow eyes dark urine pale stools fatigue abdominal pain", "Jaundice"),
    ("peeliya sharir peela aankhen peeli peshab gehra peela kamzori", "Jaundice"),
    ("yellowing of eyes skin dark colored urine loss of appetite nausea", "Jaundice"),
    ("eyes yellow skin yellow pale stool abdominal discomfort fatigue", "Jaundice"),
    ("icterus yellow sclera dark urine itching pale stools malaise", "Jaundice"),
    ("anorexia nausea yellow discoloration of skin eyes dark urine", "Jaundice"),
    ("piliya symptoms yellow eyes body weakness dark urine stomach ache", "Jaundice"),
    ("yellow skin fever nausea vomiting upper right stomach pain", "Jaundice"),
    ("skin turns yellow eyes yellow dark yellow urine fatigue weakness", "Jaundice"),
    ("hepatic jaundice yellow eyes dark urine pale stools nausea", "Jaundice"),
    ("aankhen peeli ho gayi hai peshab dark aa raha hai bhook nahi", "Jaundice"),
    ("body yellowing yellow eyes severe weakness abdominal pain dark urine", "Jaundice"),
    ("yellow sclera bilirubin high fatigue nausea pale bowel movements", "Jaundice"),
    ("skin yellowing dark urine fatigue loss of appetite right side pain", "Jaundice"),
    ("piliya rog yellow eyes skin dark urine weakness", "Jaundice"),
    ("severe jaundice yellow skin itching dark urine abdominal discomfort", "Jaundice"),
    ("yellowing eyes body skin dark urine fatigue nausea", "Jaundice"),
    ("peela rang aankhon ka peshab peela thakaan bhook kam", "Jaundice"),
    ("hyperbilirubinemia yellow eyes skin dark urine pale stool", "Jaundice"),
    ("yellow skin eyes darkening of urine extreme fatigue right abdomen pain", "Jaundice"),
    ("piliya ho gaya hai aankhen aur nakhun peele dikh rahe hain", "Jaundice"),
    ("dark tea colored urine with yellow eyes and itching all over", "Jaundice"),
    ("peshab chai jaisa aa raha hai aur aankhen bilkul peeli hain", "Jaundice"),
    ("liver problem yellow skin vomiting fatigue and stomach ache", "Jaundice"),
    ("jaundice symptoms yellow sclera dark pee loss of appetite", "Jaundice"),
    ("sharir mein peelapan thakaan aur ulti jaisa lag raha hai", "Jaundice"),
    ("yellowish skin yellow eyes fever and upper abdominal tenderness", "Jaundice"),
    ("peeliya ki shikayat aankhein peeli thakaan aur kamzori", "Jaundice"),
    ("bilirubin levels high yellow skin itching and dark urine", "Jaundice"),
    ("skin and eyes turning yellow day by day weak feeling", "Jaundice"),
    ("piliya rog hai bhook bilkul mar gayi hai aur peshab peela hai", "Jaundice"),
    ("symptoms of hepatitis yellow eyes skin and dark orange urine", "Jaundice"),
    ("aankhon ka safed hissa peela ho gaya hai kamzori bahut hai", "Jaundice"),
    ("yellow skin itchiness dark urine pale feces extreme exhaustion", "Jaundice"),
    ("sharir mein peela rang dikh raha hai thakaan aur bhook kam", "Jaundice"),
    ("icteric sclera dark yellow urine nausea vomiting right side pain", "Jaundice"),
    ("piliya ki vajah se aankhen peeli aur peshab gehra peela", "Jaundice"),
    ("yellow discoloration of eyes skin fatigue stomach pain nausea", "Jaundice"),
    ("peela sharir peeli aankhen thakaan aur khujli", "Jaundice"),
    ("obstructive jaundice yellow skin pale stools dark urine", "Jaundice"),
    ("piliya bimari aankhen aur chamdi peeli bhook nahi lagti", "Jaundice"),
    ("chronic yellow eyes dark urine loss of appetite liver infection", "Jaundice"),
    ("aankhon mein peelapan peshab ka rang badal gaya hai kamzori", "Jaundice"),
    ("yellow skin syndrome dark urine itching extreme fatigue", "Jaundice"),
    ("piliya symptoms peela chehra aankhen aur kamzori", "Jaundice"),
    ("hepatomegaly with yellow eyes dark urine and nausea", "Jaundice"),
    ("peela peshab peeli aankhen bhook ki kami thakaan", "Jaundice"),
    ("scleral icterus dark urine fatigue itching yellowing skin", "Jaundice"),
    ("piliya ki shikayat sharir bilkul peela pad gaya hai", "Jaundice"),
    ("yellowing of everything eyes skin nails with dark urine", "Jaundice"),

    # HEATSTROKE (Loo Lagna) - 50 samples (Expanded)
    ("high body temperature hot dry skin confusion rapid pulse headache dizziness", "Heatstroke"),
    ("loo lag gayi high fever garmi se chakkar behoshi dry skin", "Heatstroke"),
    ("sunstroke high temp no sweating red hot dry skin rapid heartbeat", "Heatstroke"),
    ("fainting high temperature confusion dizziness muscle weakness in sun", "Heatstroke"),
    ("hyperthermia heat stroke confusion high pulse dry skin throbbing headache", "Heatstroke"),
    ("severe headache nausea dizziness high body temp after sun exposure", "Heatstroke"),
    ("loo lagna bukhaar bahut tez pulse chakkar aana sukhi chamdi", "Heatstroke"),
    ("high fever hot weather confusion rapid breathing dizziness headache", "Heatstroke"),
    ("sun stroke symptoms red dry skin high fever mental confusion", "Heatstroke"),
    ("heat exhaustion dizziness fainting high body temperature rapid pulse", "Heatstroke"),
    ("dhoop mein rahne se bukhar chakkar behoshi sar dard pulse tez", "Heatstroke"),
    ("severe heatstroke high fever confusion delirium dry skin rapid pulse", "Heatstroke"),
    ("hot dry skin temperature 104 or more dizziness rapid breathing", "Heatstroke"),
    ("sunburn heatstroke fever confusion nausea vomiting after sun", "Heatstroke"),
    ("garmi se tabiyat kharab tez bukhar chakkar thakaan sukhi skin", "Heatstroke"),
    ("heat injury high temp confusion tachycardia dry red skin", "Heatstroke"),
    ("fever after working in sun confusion dizziness dry skin headache", "Heatstroke"),
    ("loo lagne se bukhar behoshi chakkar thakaan pulse tez", "Heatstroke"),
    ("high body temp over 40C confusion rapid pulse dry skin no sweat", "Heatstroke"),
    ("sunstroke high fever hot skin nausea vomiting headache confusion", "Heatstroke"),
    ("garmi ki vajah se chakkar aur tez bukhar skin bilkul sukhi", "Heatstroke"),
    ("heat stroke high fever confusion rapid heart rate no sweating", "Heatstroke"),
    ("dhoop mein kaam kiya ab bukhar hai aur sar ghoom raha hai", "Heatstroke"),
    ("hot red skin with high fever and confusion after outdoors", "Heatstroke"),
    ("loo lag gayi hai sharir garam hai par paseena nahi aa raha", "Heatstroke"),
    ("severe hyperthermia from sun exposure confusion rapid pulse", "Heatstroke"),
    ("dhoop ki tapish se bukhar behoshi aur sar mein tez dard", "Heatstroke"),
    ("heatstroke symptoms high temp dry skin mental confusion nausea", "Heatstroke"),
    ("loo lagne se tabiyat bigad gayi tez bukhar aur chakkar", "Heatstroke"),
    ("fever 105 degrees hot dry skin confusion after sun stroke", "Heatstroke"),
    ("garmi mein bahar jane se bukhar aur behoshi jaisa lag raha hai", "Heatstroke"),
    ("sunstroke high body temperature no sweat red hot skin", "Heatstroke"),
    ("loo ka asar tez bukhar dry chamdi aur darr lag raha hai", "Heatstroke"),
    ("heat exhaustion leading to stroke high temp confusion dizziness", "Heatstroke"),
    ("dhoop mein chakkar aa kar gir gaya bukhar bahut tez hai", "Heatstroke"),
    ("dry hot skin high pulse confusion after working in heat", "Heatstroke"),
    ("garmi se bukhar aur sar dard paseena bilkul band ho gaya", "Heatstroke"),
    ("heatstroke warning signs high temp confusion rapid breathing", "Heatstroke"),
    ("loo lagne se sharir tap raha hai chakkar aa rahe hain", "Heatstroke"),
    ("sunstroke symptoms dizziness vomiting high fever dry skin", "Heatstroke"),
    ("bahar dhoop mein rahne se bukhar aur sar ghoom raha hai", "Heatstroke"),
    ("extreme heat injury high temp confusion dry red skin", "Heatstroke"),
    ("loo ki vajah se behoshi aur tez bukhar skin garam hai", "Heatstroke"),
    ("heatstroke recovery need high temp confusion rapid pulse", "Heatstroke"),
    ("garmi se sar dard ulti aur tez bukhar paseena nahi", "Heatstroke"),
    ("sun stroke red dry skin confusion fast heartbeat high fever", "Heatstroke"),
    ("dhoop mein sar dard aur bukhar ho gaya loo lag gayi", "Heatstroke"),
    ("heatstroke emergency high fever no sweating confusion", "Heatstroke"),
    ("loo lag gayi hai bukhar 104 hai aur chakkar aa rahe hain", "Heatstroke"),
    ("sunstroke hot skin confusion rapid pulse high temperature", "Heatstroke"),

    # SNAKEBITE (Saamp ka kaatna) - 50 samples (Expanded)
    ("snake bite puncture marks severe pain swelling blurred vision numbness", "Snakebite"),
    ("saamp ne kaata dard sujan dhundhla dikhna saans lene mein takleef", "Snakebite"),
    ("venomous bite two puncture wounds swelling bruising pain numbness", "Snakebite"),
    ("cobra bite paralysis difficulty breathing drooping eyelids rapid pulse", "Snakebite"),
    ("viper bite severe pain rapid swelling bleeding from wound vomiting", "Snakebite"),
    ("snakebite site swelling pain nausea weakness metallic taste in mouth", "Snakebite"),
    ("saamp ka katna nishan dard sujan kamzori saans lene mein dikkat", "Snakebite"),
    ("puncture marks intense pain spreading swelling numbness dizziness", "Snakebite"),
    ("ophitoxemia snake bite swelling localized pain bleeding nausea", "Snakebite"),
    ("bite from snake swelling around wound extreme pain blurred vision", "Snakebite"),
    ("saamp ke dant ke nishan dard sujan nasha saans mein dikkat", "Snakebite"),
    ("snake envenomation swelling pain difficulty swallowing paralysis signs", "Snakebite"),
    ("two puncture marks bite site swelling pain nausea sweating", "Snakebite"),
    ("venomous snake bite severe local pain edema bruising numbness", "Snakebite"),
    ("saamp kaat gaya sujan hai dard hai dhundhla dikh raha hai", "Snakebite"),
    ("serpent bite localized swelling pain weakness difficulty breathing", "Snakebite"),
    ("snakebite symptoms pain swelling around bite site nausea dizziness", "Snakebite"),
    ("saamp ka nishan sujan tez dard kamzori saans lene mein takleef", "Snakebite"),
    ("neurotoxic snake bite paralysis drooping eyes respiratory distress", "Snakebite"),
    ("haemotoxic snake bite bleeding swelling extreme pain around bite", "Snakebite"),
    ("saamp ne pair mein kaat liya hai do nishan hain aur sujan hai", "Snakebite"),
    ("snake bit my hand swelling spreading fast and feeling dizzy", "Snakebite"),
    ("saamp kaatne ke baad aankhon ke samne andhera aur sujan", "Snakebite"),
    ("poisonous snake bite swelling pain nausea and breathing problem", "Snakebite"),
    ("khet mein saamp ne kaata ab pair neela pad raha hai aur dard hai", "Snakebite"),
    ("snakebite puncture wounds swelling numbness and blurred vision", "Snakebite"),
    ("saamp ne kaat liya hai saans lene mein bahut takleef ho rahi hai", "Snakebite"),
    ("envenomation symptoms swelling pain bleeding from bite site", "Snakebite"),
    ("saamp ka nishan sujan aur kamzori saans phul rahi hai", "Snakebite"),
    ("cobra bite signs paralysis drooping eyelids difficulty breathing", "Snakebite"),
    ("saamp ne kaata hai dard bahut tez hai aur ulti aa rahi hai", "Snakebite"),
    ("snakebite emergency swelling pain numbness spreading to body", "Snakebite"),
    ("pair mein saamp ka nishan do chhed dikh rahe hain sujan hai", "Snakebite"),
    ("venomous bite site swelling discoloration extreme pain nausea", "Snakebite"),
    ("saamp ne kaat liya pair bhari ho gaya hai aur dikhna kam ho gaya", "Snakebite"),
    ("snakebite wound swelling bruising intense pain dizziness", "Snakebite"),
    ("saamp ke katne se sujan dard aur saans lene mein dikkat", "Snakebite"),
    ("neurotoxic symptoms after snake bite paralysis respiratory failure", "Snakebite"),
    ("saamp kaatne ke baad shareer thanda pad raha hai aur sujan hai", "Snakebite"),
    ("snakebite site redness swelling intense pain and sweating", "Snakebite"),
    ("saamp ne kaat liya hai dard aur sujan badhti ja rahi hai", "Snakebite"),
    ("viper bite signs rapid swelling bleeding pain vomiting", "Snakebite"),
    ("saamp ka katna pair mein sujan aur dhundhla dikhai dena", "Snakebite"),
    ("snakebite puncture marks with swelling and local pain", "Snakebite"),
    ("saamp ne khet mein kaata ab nasha sa lag raha hai aur sujan hai", "Snakebite"),
    ("poisonous bite swelling around puncture marks severe pain", "Snakebite"),
    ("saamp kaat gaya sujan aur dard se bura haal hai", "Snakebite"),
    ("snakebite symptoms local swelling pain weakness blurred vision", "Snakebite"),
    ("saamp ne kaata hai pair sujan se phul gaya hai aur dard hai", "Snakebite"),
    ("venomous snake bite marks with rapid swelling and pain", "Snakebite"),

    # ANEMIA (Khoon ki kami) - 50 samples (Expanded)
    ("pale skin extreme fatigue weakness dizziness shortness of breath brittle nails", "Anaemia"),
    ("khoon ki kami safed sharir kamzori chakkar saans fulna thakaan", "Anaemia"),
    ("pallor fatigue weakness headache cold hands feet chest pain", "Anaemia"),
    ("iron deficiency pale skin weakness shortness of breath fast heartbeat", "Anaemia"),
    ("anaemia symptoms low hemoglobin pale face extreme tiredness", "Anaemia"),
    ("fatigue lightheadedness pale skin brittle nails sore tongue", "Anaemia"),
    ("sharir mein khoon kam hai thakaan chakkar saans fulna kamzori", "Anaemia"),
    ("pale conjunctiva fatigue weakness shortness of breath on exertion", "Anaemia"),
    ("low blood count pale skin weakness dizziness fast pulse rate", "Anaemia"),
    ("severe anemia fatigue pallor shortness of breath pica symptoms", "Anaemia"),
    ("safedi sharir mein kamzori thakaan jaldi saans fulna chakkar", "Anaemia"),
    ("erythropenia pale skin fatigue generalized weakness brittle nails", "Anaemia"),
    ("pale skin low energy weakness headache dizziness heart palpitations", "Anaemia"),
    ("tired all the time pale skin shortness of breath weakness", "Anaemia"),
    ("khoon kam hai kamzori lagti hai saans phulti hai thakaan", "Anaemia"),
    ("anemia fatigue weakness pale complexion dizziness fast heartbeat", "Anaemia"),
    ("iron deficiency anemia pale tongue brittle nails fatigue weakness", "Anaemia"),
    ("kamzori thakaan sharir peela saans lene mein dikkat chakkar", "Anaemia"),
    ("pallor of skin mucous membranes fatigue weakness dyspnea", "Anaemia"),
    ("very low iron fatigue weakness pale skin cold extremities", "Anaemia"),
    ("sharir bilkul safed dikh raha hai kamzori bahut hai", "Anaemia"),
    ("anemic symptoms pale face dizziness extreme tiredness", "Anaemia"),
    ("khoon ki kami ki vajah se chakkar aur saans phulna", "Anaemia"),
    ("pallor skin fatigue weakness and heart palpitations", "Anaemia"),
    ("bahut thakaan rehti hai aur chehra peela pad gaya hai", "Anaemia"),
    ("severe anemia pale conjunctiva weakness brittle nails", "Anaemia"),
    ("khoon kam ho gaya hai sharir mein jaan nahi lagti", "Anaemia"),
    ("fatigue shortness of breath pale skin low iron levels", "Anaemia"),
    ("chehre par peelapan aur thoda sa kaam karne par saans fulna", "Anaemia"),
    ("anemia signs pale skin weakness dizziness fatigue", "Anaemia"),
    ("sharir peela aur safed sa dikh raha hai thakaan bahut hai", "Anaemia"),
    ("pallor weakness dizziness shortness of breath anemia", "Anaemia"),
    ("khoon ki kami se chakkar aana aur kamzori mahsoos karna", "Anaemia"),
    ("brittle nails pale skin fatigue shortness of breath", "Anaemia"),
    ("chehra peela hai aur hamesha thakaan rehti hai", "Anaemia"),
    ("iron deficiency signs pale skin fatigue low energy", "Anaemia"),
    ("safed chehra aur bahut zyada thakaan khoon ki kami", "Anaemia"),
    ("pale appearance with dizziness and shortness of breath", "Anaemia"),
    ("khoon ki kami hai sharir mein jaan nahi saans phulna", "Anaemia"),
    ("tiredness and pale eyes signs of low hemoglobin", "Anaemia"),
    ("chehra peela pad jana aur thoda chalne par saans fulna", "Anaemia"),
    ("anemia fatigue weakness pale skin cold hands", "Anaemia"),
    ("sharir mein khoon kam ho gaya hai thakaan rehti hai", "Anaemia"),
    ("pale face and weakness with rapid heartbeat anemia", "Anaemia"),
    ("safed skin aur kamzori ki shikayat khoon ki kami", "Anaemia"),
    ("anemia symptoms dizziness fatigue and pale conjunctiva", "Anaemia"),
    ("khoon ki kami se hone wali thakaan aur saans phulna", "Anaemia"),
    ("pale skin symptoms low iron weakness and fatigue", "Anaemia"),
    ("chehra peela dikh raha hai aur kamzori bahut hai", "Anaemia"),
    ("anemia signs weakness fatigue and pale face appearance", "Anaemia"),
    ("sharir mein khoon ki kami hai thakaan aur chakkar aate hain", "Anaemia"),
    ("anemic weakness pale skin lightheadedness fatigue", "Anaemia"),
    ("hathon aur pairon mein thandak aur chehra peela", "Anaemia"),
    ("pale tongue pale skin fatigue weakness anemia", "Anaemia"),
    ("khoon kam hone se kamzori aur saans lene mein takleef", "Anaemia"),
    ("tiredness pale face dizziness shortness of breath", "Anaemia"),
    ("sharir bilkul peela pad gaya hai kamzori bahut hai", "Anaemia"),
    ("pallor of skin fatigue low iron count weakness", "Anaemia"),
    ("khoon ki kami symptoms chehra peela thakaan kamzori", "Anaemia"),
    ("extreme fatigue pale skin dizziness anemia", "Anaemia"),
    ("sharir mein khoon ki kami thakaan aur saans fulna", "Anaemia"),
    ("pale skin weakness shortness of breath low hemoglobin", "Anaemia"),
    ("kamzori thakaan peela chehra khoon ki kami", "Anaemia"),
    ("anemia symptoms fatigue pale skin dizziness weakness", "Anaemia"),

    # SKIN INFECTION (Scabies/Fungal/Khujli) - 50 samples (Expanded)
    ("intense itching rash small bumps sores on skin rural hygiene issues", "Skin Infection"),
    ("khujli rash sharir par daane jalan skin infection khurachne se zakham", "Skin Infection"),
    ("scabies rash severe itching at night red bumps between fingers", "Skin Infection"),
    ("fungal infection red itchy circular patches on skin burning sensation", "Skin Infection"),
    ("dermatitis skin rash itching redness scaling of skin crusting", "Skin Infection"),
    ("eczema itchy dry skin red patches sores from scratching", "Skin Infection"),
    ("khujli ho rahi hai daane nikal aaye hain sharir par jalan", "Skin Infection"),
    ("intense pruritus skin rash red papules pustules sores on skin", "Skin Infection"),
    ("tinea infection red itchy rash skin peeling burning feeling", "Skin Infection"),
    ("bacterial skin infection redness swelling pain warmth pus", "Skin Infection"),
    ("daad khaaj khujli red patches rash sharir par daane", "Skin Infection"),
    ("impetigo red sores yellow crusts on skin itching fluid filled bumps", "Skin Infection"),
    ("psoriasis itchy silver scales red patches of skin dry cracked", "Skin Infection"),
    ("skin rash severe itching red spots on body scratching causes sores", "Skin Infection"),
    ("sharir mein khujli rash daane purani khujli jalan", "Skin Infection"),
    ("scabies symptoms nocturnal itching red rash papules skin burrows", "Skin Infection"),
    ("dermatophytosis red itchy rings on skin scaling inflammation", "Skin Infection"),
    ("khujli wale daane rash jalan skin laal ho gayi hai", "Skin Infection"),
    ("urticaria itchy red welts on skin hives rash burning sensation", "Skin Infection"),
    ("folliculitis red itchy bumps around hair follicles skin infection", "Skin Infection"),
    ("sharir par purani khujli hai aur daane nikal rahe hain", "Skin Infection"),
    ("skin infection itching red patches and small sores on body", "Skin Infection"),
    ("daad ho gaya hai gol chakte aur bahut khujli hoti hai", "Skin Infection"),
    ("fungal skin rash red circles itching and burning sensation", "Skin Infection"),
    ("khujli ki vajah se chamdi laal ho gayi hai aur dard hai", "Skin Infection"),
    ("bacterial infection on skin redness pus and swelling", "Skin Infection"),
    ("sharir mein jagah jagah khujli aur daane nikal aaye hain", "Skin Infection"),
    ("scabies infection severe itching red bumps on skin", "Skin Infection"),
    ("khujli wale nishan sharir par aur jalan mahsoos ho rahi hai", "Skin Infection"),
    ("dermatitis rash red itchy dry skin patches on body", "Skin Infection"),
    ("daad ki shikayat gol laal nishan aur bahut khujli", "Skin Infection"),
    ("skin rash symptoms redness itching small fluid filled bumps", "Skin Infection"),
    ("purani khujli daane aur chamdi ka rang badal raha hai", "Skin Infection"),
    ("fungal infection red itchy spots on skin rural health", "Skin Infection"),
    ("khujli se bura haal hai daane aur jalan bahut hai", "Skin Infection"),
    ("eczema rash dry itchy red skin on hands and legs", "Skin Infection"),
    ("sharir par daane khujli aur skin laal ho gayi hai", "Skin Infection"),
    ("psoriasis signs silver scales red patches itchy skin", "Skin Infection"),
    ("khujli ho rahi hai raat ko badh jati hai daane hain", "Skin Infection"),
    ("bacterial skin infection red painful swelling with pus", "Skin Infection"),
    ("daad khaaj ki bimari laal nishan aur khujli", "Skin Infection"),
    ("itchy red rash on skin small papules and sores", "Skin Infection"),
    ("khujli wale chakte sharir par aur jalan", "Skin Infection"),
    ("ringworm fungal infection red itchy circular rash", "Skin Infection"),
    ("daane hain sharir par aur bahut khujli hoti hai", "Skin Infection"),
    ("scabies rash symptoms itching red bumps between fingers", "Skin Infection"),
    ("khujli aur jalan sharir par daane nikal rahe hain", "Skin Infection"),
    ("skin infection signs redness itching sores and crusting", "Skin Infection"),
    ("daad ki vajah se bahut pareshan hoon khujli bahut hai", "Skin Infection"),
    ("itchy skin rash red spots and dry patches on body", "Skin Infection"),

    # UTI (Urinary Tract Infection / Peshaab mein jalan) - 50 samples (Expanded)
    ("burning urination frequent urge to pee pelvic pain cloudy urine strong odor", "UTI"),
    ("peshab mein jalan baar baar peshab aana pet ke nichle hisse mein dard", "UTI"),
    ("painful urination frequent urination pressure in lower abdomen cloudy pee", "UTI"),
    ("cystitis burning sensation when peeing frequent urge pelvic discomfort", "UTI"),
    ("urinary infection painful pee cloudy smelly urine lower back pain", "UTI"),
    ("burning during urination urge to pee frequently pelvic pressure", "UTI"),
    ("peshab karte waqt jalan baar baar peshab jana pet mein dard", "UTI"),
    ("dysuria frequent urination pelvic pain hematuria cloudy urine", "UTI"),
    ("burning urination urgency frequent small amounts of urine pelvic ache", "UTI"),
    ("uti symptoms burning pee frequent urge lower abdominal pain", "UTI"),
    ("peshab mein jalan thoda thoda peshab aana baar baar jana", "UTI"),
    ("pyelonephritis kidney pain fever chills painful urination nausea", "UTI"),
    ("strong persistent urge to urinate burning sensation cloudy urine", "UTI"),
    ("pain while passing urine frequent urge pelvic discomfort weakness", "UTI"),
    ("jaldi jaldi peshab aana jalan ke sath pet ke niche dard", "UTI"),
    ("urethritis burning urination discharge frequent urge pelvic pain", "UTI"),
    ("burning urination strong smelling urine frequent small volumes", "UTI"),
    ("peshab mein bahut jalan baar baar jane ki aadat pet dard", "UTI"),
    ("lower urinary tract infection burning pee frequency urgency", "UTI"),
    ("painful burning urination frequent small amounts of pee pelvic pressure", "UTI"),
    ("peshab mein bahut jalan hai aur baar baar jana padta hai", "UTI"),
    ("burning sensation while urinating with lower belly pain", "UTI"),
    ("peshab ruk ruk kar aa raha hai aur jalan bahut hai", "UTI"),
    ("uti infection burning pee frequent urge cloudy urine", "UTI"),
    ("pet के निचले हिस्से में दर्द और पेशाब में जलन", "UTI"),
    ("painful urination with frequent urge to pee pelvic pressure", "UTI"),
    ("peshab mein jalan aur dard baar baar peshab ki shikayat", "UTI"),
    ("cystitis symptoms burning urination frequent small amounts", "UTI"),
    ("pishab mein jalan thoda thoda peshab aur dard", "UTI"),
    ("urinary tract infection signs burning pee pelvic pain", "UTI"),
    ("peshab karte samay jalan aur pet mein मरोड़", "UTI"),
    ("burning urination frequent urge lower abdominal ache", "UTI"),
    ("peshab mein jalan hai aur bahut takleef hoti hai", "UTI"),
    ("uti pain burning urination frequent trips to bathroom", "UTI"),
    ("peshab mein jalan aur rukan baar baar jana pad raha hai", "UTI"),
    ("painful pee burning sensation frequent urge to urinate", "UTI"),
    ("peshab mein jalan aur pet ke niche dard thoda peshab", "UTI"),
    ("burning micturition frequent urge pelvic discomfort", "UTI"),
    ("peshab mein jalan ki vajah se pareshani baar baar peshab", "UTI"),
    ("uti symptoms burning urination frequent urge smelly urine", "UTI"),
    ("peshab mein jalan aur kadi dhaar nahi thoda thoda", "UTI"),
    ("burning urination pelvic pain frequent urge to pee", "UTI"),
    ("peshab mein jalan ho rahi hai aur pet dard bhi hai", "UTI"),
    ("painful urination signs burning frequent urge pelvic ache", "UTI"),
    ("peshab mein jalan aur baar baar peshab ka ana", "UTI"),
    ("uti burning sensation when peeing frequent urge pelvic pain", "UTI"),
    ("peshab karte waqt bahut jalan aur pet niche dard", "UTI"),
    ("burning pee frequent urination pressure in lower abdomen", "UTI"),
    ("peshab mein jalan aur thakaan baar baar peshab", "UTI"),
    ("painful urination symptoms burning frequent urge to pee", "UTI"),

    # VIRAL FEVER / MALARIA / TYPHOID Expanded to 50 combined
    ("high fever with chills body ache headache and weakness", "Viral Fever"),
    ("bukhar thakaan sharir dard aur sar mein dard", "Viral Fever"),
    ("fever chills body ache fatigue weakness viral infection", "Viral Fever"),
    ("tez bukhar sharir mein dard aur bahut kamzori", "Viral Fever"),
    ("high fever headache nausea body ache weakness", "Viral Fever"),
    ("bukhar sar dard aur thakaan sharir toot raha hai", "Viral Fever"),
    ("viral fever symptoms high temp body ache weakness", "Viral Fever"),
    ("bukhar hai aur sharir mein bahut dard hai thakaan", "Viral Fever"),
    ("fever chills headache fatigue muscle pain", "Viral Fever"),
    ("tez bukhar sar dard thakaan kamzori mahsoos ho rahi hai", "Viral Fever"),
    ("high fever with shivering every evening and headache", "Malaria"),
    ("ek din chhod kar bukhar thand lag kar aur sar dard", "Malaria"),
    ("malaria symptoms chills high fever sweating headache", "Malaria"),
    ("thand lag kar tez bukhar paseena ana aur kamzori", "Malaria"),
    ("intermittent fever with chills headache and body ache", "Malaria"),
    ("bukhar thand ke sath aur thakaan malaria ki shikayat", "Malaria"),
    ("high fever shivering sweating headache malaria", "Malaria"),
    ("thand lag kar bukhar ana aur thakaan kamzori", "Malaria"),
    ("periodical fever chills headache sweating weakness", "Malaria"),
    ("malaria signs high fever shivering and body pain", "Malaria"),
    ("fever headache stomach pain and constipation for 1 week", "Typhoid"),
    ("ek hafte se bukhar pet mein dard aur kabz", "Typhoid"),
    ("typhoid symptoms continuous fever stomach pain headache", "Typhoid"),
    ("roz bukhar badh raha hai pet dard aur bhook nahi", "Typhoid"),
    ("continuous high fever for many days stomach pain weak", "Typhoid"),
    ("bukhar jo kam nahi ho raha pet dard aur kamzori", "Typhoid"),
    ("typhoid fever headache abdominal pain constipation", "Typhoid"),
    ("hafte bhar se bukhar pet mein dard aur thakaan", "Typhoid"),
    ("sustained fever slow pulse stomach pain typhoid", "Typhoid"),
    ("bukhar hafte se badh raha hai pet mein dard aur kamzori", "Typhoid"),
    # Additional 20 for core
    ("high temp chills body ache weakness fever", "Viral Fever"),
    ("malaria chills high temp headache sweating", "Malaria"),
    ("typhoid long fever stomach ache weakness", "Typhoid"),
    ("viral infection fever body pain thakaan", "Viral Fever"),
    ("thand wala bukhar malaria chills headache", "Malaria"),
    ("pet dard hafte se bukhar typhoid constipation", "Typhoid"),
    ("tez bukhar sharir dard thakaan viral", "Viral Fever"),
    ("shivering fever headache malaria signs", "Malaria"),
    ("step ladder fever stomach pain typhoid", "Typhoid"),
    ("fever weakness headache body ache", "Viral Fever"),
    ("thand lag kar bukhar malaria symptoms", "Malaria"),
    ("hafte se bukhar pet dard typhoid signs", "Typhoid"),
    ("viral fever high temp weakness body ache", "Viral Fever"),
    ("malaria fever chills sweating headache", "Malaria"),
    ("typhoid fever stomach pain constipation headache", "Typhoid"),
    ("bukhar thakaan sharir mein dard viral", "Viral Fever"),
    ("thand wala bukhar malaria symptoms chills", "Malaria"),
    ("typhoid signs long fever stomach pain", "Typhoid"),
    ("viral infection high fever body ache", "Viral Fever"),
    ("malaria high fever chills sweating weakness", "Malaria"),
]

if __name__ == "__main__":
    df = pd.DataFrame(TRAINING_DATA, columns=["symptoms", "disease"])
    print(f"[OK] Dataset: {len(df)} samples, {df['disease'].nunique()} classes")
    print(f"   Per class: min={df['disease'].value_counts().min()}, max={df['disease'].value_counts().max()}\n")

    X, y = df["symptoms"], df["disease"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # Two complementary estimators:
    # RF  — captures term co-occurrences, generalises across symptom phrasing
    # GB  — boosts on hard/misclassified edge cases, improves precision on rare diseases
    rf  = RandomForestClassifier(n_estimators=250, max_depth=50, min_samples_split=3,
                                  class_weight="balanced", random_state=42, n_jobs=-1)
    gb  = GradientBoostingClassifier(n_estimators=150, learning_rate=0.08,
                                      max_depth=6, random_state=42)
    voting = VotingClassifier(estimators=[("rf", rf), ("gb", gb)], voting="soft", weights=[2, 1])

    pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_features=5000, sublinear_tf=True)),
        ("clf", voting)
    ])

    print("[...] Training RF+GradientBoosting Ensemble (soft-voting)...")
    pipeline.fit(X_train, y_train)

    # Cross-validation for honest accuracy
    cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring="accuracy")
    print(f"[OK] 5-Fold Cross-Val Accuracy: {cv_scores.mean()*100:.1f}% (+/- {cv_scores.std()*100:.1f}%)")

    y_pred = pipeline.predict(X_test)
    test_acc = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, zero_division=0)
    print(f"[RESULT] Test Accuracy: {test_acc * 100:.1f}%")
    print(report)

    joblib.dump(pipeline, "disease_model.pkl")
    print("[SAVED] disease_model.pkl")

    with open("model_accuracy.txt", "w") as f:
        f.write("SwasthAI Guardian - Disease Prediction Model\n")
        f.write("=" * 50 + "\n")
        f.write(f"Algorithm     : Random Forest Classifier\n")
        f.write(f"Vectorizer    : TF-IDF (unigrams + bigrams)\n")
        f.write(f"Training set  : {len(X_train)} samples\n")
        f.write(f"Test set      : {len(X_test)} samples\n")
        f.write(f"CV Accuracy   : {cv_scores.mean()*100:.1f}% (+/- {cv_scores.std()*100:.1f}%)\n")
        f.write(f"Test Accuracy : {test_acc * 100:.1f}%\n")
        if df['disease'].nunique(): f.write(f"Disease Classes ({df['disease'].nunique()}): {sorted(df['disease'].unique())}\n\n")
        f.write(f"Classification Report:\n{report}\n")

    print("[DONE] Model ready. Restart main.py (uvicorn) to use it.")

